# Generated by Django 3.1.12 on 2025-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('DR_NO', models.IntegerField(unique=True)),
                ('Date_Rptd', models.DateField()),
                ('DATE_OCC', models.DateField()),
                ('TIME_OCC', models.TimeField()),
                ('AREA', models.IntegerField()),
                ('AREA_NAME', models.CharField(max_length=100)),
                ('Rpt_Dist_No', models.IntegerField()),
                ('Crm_Cd', models.IntegerField()),
                ('Crm_Cd_Desc', models.CharField(max_length=100)),
                ('Mocodes', models.TextField()),
                ('Vict_Age', models.IntegerField(null=True)),
                ('Vict_Sex', models.CharField(max_length=5, null=True)),
                ('Vict_Descent', models.CharField(max_length=5, null=True)),
                ('Premis_Cd', models.IntegerField()),
                ('Premis_Desc', models.CharField(max_length=100)),
                ('Weapon_Used_Cd', models.IntegerField(default=0)),
                ('Weapon_Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(max_length=2)),
                ('Status_Desc', models.CharField(max_length=15)),
                ('Crm_Cd_1', models.IntegerField()),
                ('Crm_Cd_2', models.IntegerField(blank=True, null=True)),
                ('Crm_Cd_3', models.IntegerField(blank=True, null=True)),
                ('Crm_Cd_4', models.IntegerField(blank=True, null=True)),
                ('LOCATION', models.CharField(max_length=200)),
                ('Cross_Street', models.CharField(blank=True, max_length=200, null=True)),
                ('LAT', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('LON', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeReportTest',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('DR_NO', models.IntegerField(unique=True)),
                ('Date_Rptd', models.CharField(max_length=100)),
                ('DATE_OCC', models.CharField(max_length=100)),
                ('TIME_OCC', models.IntegerField()),
                ('AREA', models.IntegerField()),
                ('AREA_NAME', models.CharField(max_length=100)),
                ('Rpt_Dist_No', models.IntegerField()),
                ('Crm_Cd', models.IntegerField()),
                ('Crm_Cd_Desc', models.CharField(max_length=100)),
                ('Mocodes', models.CharField(max_length=100)),
                ('Vict_Age', models.IntegerField()),
                ('Vict_Sex', models.CharField(max_length=1)),
                ('Vict_Descent', models.CharField(max_length=1)),
                ('Premis_Cd', models.FloatField()),
                ('Premis_Desc', models.CharField(max_length=100)),
                ('Weapon_Used_Cd', models.IntegerField()),
                ('Weapon_Desc', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=2)),
                ('Status_Desc', models.CharField(max_length=100)),
                ('Crm_Cd_1', models.FloatField()),
                ('Crm_Cd_2', models.FloatField()),
                ('Crm_Cd_3', models.IntegerField()),
                ('Crm_Cd_4', models.IntegerField()),
                ('LOCATION', models.CharField(max_length=200)),
                ('Cross_Street', models.CharField(max_length=200)),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('badge_number', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
