# Generated by Django 3.1.12 on 2025-01-14 20:18

import crime_app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('DR_NO', models.IntegerField(unique=True)),
                ('Mocodes', models.TextField()),
                ('date_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.DateObject)),
                ('area_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.AreaObject)),
                ('crime_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.CrimeObject)),
                ('victim_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.VictimObject)),
                ('premise_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.PremiseObject)),
                ('weapon_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.WeaponObject)),
                ('status_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.StatusObject)),
                ('location_object', djongo.models.fields.EmbeddedField(model_container=crime_app.models.LocationObject)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('badge_number', models.CharField(max_length=50)),
                ('upvote_details', djongo.models.fields.ArrayField(blank=True, default=[], model_container=crime_app.models.OfficerUpvote)),
            ],
        ),
    ]
