# Generated by Django 3.1.12 on 2025-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
