# Generated by Django 3.1.12 on 2025-01-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
